export const beveragesObjOne = {
    id: 'beverages',
    lightBg: true,
    lightText: false,
    lighttextDesc: false,
    headline: 'Beverages',
    buttonLabel1: 'Coke',
    buttonLabel2: 'Dr Pepper',
    buttonLabel3: 'Seven Up',
    buttonLabel4: 'Bargs',
    buttonLabel5: 'Sweet Tea',
    buttonLabel6: 'Diet Tea',
    buttonLabel7: 'Water',
    imgStart: false,
    img: require('../../images/rusticsoda.png').default,
    alt: 'Pizza',
    dark: false,
    primary: false,
    darkText: true
  };